---
deployment:
  tasks:
    - export DEPLOYPATH=/home/recipco1/repositories/ECO-Capacity-api/
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R middleware $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R utils $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --omit=dev
    - cd $DEPLOYPATH && ./node_modules/.bin/pm2 restart eco-backend || ./node_modules/.bin/pm2 start server.js --name eco-backend
    - cd $DEPLOYPATH && ./node_modules/.bin/pm2 save