# deployment:
#   tasks:

#     # ==========================================
#     # PATH
#     # ==========================================
#     - export DEPLOYPATH=/home/recipco1/repositories/ECO-Capacity-api

#     # ==========================================
#     # COPY APPLICATION FILES
#     # ==========================================
#     - /bin/cp -R controllers $DEPLOYPATH
#     - /bin/cp -R middleware $DEPLOYPATH
#     - /bin/cp -R models $DEPLOYPATH
#     - /bin/cp -R routes $DEPLOYPATH
#     - /bin/cp -R utils $DEPLOYPATH
#     - /bin/cp -R config $DEPLOYPATH

#     - /bin/cp server.js $DEPLOYPATH
#     - /bin/cp package.json $DEPLOYPATH
#     - /bin/cp package-lock.json $DEPLOYPATH

#     # ==========================================
#     # INSTALL DEPENDENCIES
#     # ==========================================
#     - cd $DEPLOYPATH && npm install --omit=dev

#     # ==========================================
#     # PASSENGER RESTART
#     # ==========================================
#     - cd $DEPLOYPATH && mkdir -p tmp
#     - cd $DEPLOYPATH && touch tmp/restart.txt

#     # ==========================================
#     # VERIFY
#     # ==========================================
#     - cd $DEPLOYPATH && node -v
#     - cd $DEPLOYPATH && npm -v