name: Deploy ECO Capacity Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script: |
            set -e

            cd /home/recipco1/repositories/ECO-Capacity-api

            echo "Pulling latest code..."
            git pull origin main

            echo "Creating .env..."

            cat > .env << 'EOF'
            PORT=${{ secrets.PORT }}
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            EOF

            chmod 600 .env

            echo "Installing dependencies..."
            npm install

            echo "Restarting backend..."

            npx pm2 restart eco-backend --update-env

            echo "Saving PM2..."
            npx pm2 save

            echo "Deployment completed!"

            npx pm2 status